/*
 * Configuration for the morio_healthchecks handler
 * This handler relies on the Morio Tap server to tap into the data stream
 */
export const config = {
  handler: {
    topic: 'checks',
    filter: false,
  },
  upValues: [ "1", "up", "green" ],
  onDownProduce: 'notification',
  cache: true,
  checkCertificates: true,
}

export const docs = {
  name: 'Morio Healtchchecks Handler',
  description: `
This stream processing handler processes Morio healthchecks, which under the hood are generated by Elastic Heartbeat.

It will validate the healthcheck, and can produce a notification in case the healthcheck fails.
It can also check certificate expiry and cache the healthcheck results for dashboarding.

This handler can be further configured to control its behaviour.`,
  config: {
    upValues: "These are all the values that are considered a success for a healthcheck.",
    topic: "The topic to subscribe to. Typically 'checks'.",
    filter: "An optional filter message to use to filter messages in the topic.",
    onDownProduce: "What type of message to produce when a healthcheck fails. One of 'notification' or 'alarm'",
    cache: "Whether or not to cache healthcheck results.",
    checkCertificates: "Whether or not to verify the expiration date of TLS certificates (HTTP only)",
  }
}
