import { config } from "./morio_watcher_healthchecks.config.mjs"

/*
 * This is a Morio handler to process healthchecks
 * data generated by the Morio Watcher service.
 * It can create a notification (or alarm) when something
 * is down, and will also cache the healthcheck data for
 * dashboarding, as well as verify the expiry date of any
 * TLS certificates.
 */
const handler = {
  ...config.handler,
  method: ({ data }, tools) => {
    /*
     * Only handle data that is in the correct format
     */
    if (!data?.monitor?.id || !data?.monitor?.name) return tools.log.debug(data, 'Invalid healthcheck data')

    /*
     * Figure out what's going on.
     *   up: Whether the healthcheck is up (ok) or not (0 or 1)
     *   ms: Time in milliseconds that it took (useful observability signal)
     *   dbce: Days before certificate expires (only for https checks)
     */
    const [up, ms, dbce] = healthcheckSummary(data, tools)
    const time = tools.time.when(data)
    if (!up && ['alarm', 'notification'].includes(config.onDownProduce)) {
      // Prepare the nessage data
      const msg_data = {
        context: tools.create.context('healthcheck', data.monitor.type, data.monitor.id, tools.format.escape(data.url?.full)),
        host: data.host?.id,
        module: data.morio?.module?.name,
        tags: [ 'healthcheck', 'down', data.monitor.type, data.monitor.id ],
        time,
        title: `Healthcheck failed: ${data.url?.full}`,
        type: `${data.monitor.type}.healthcheck.down`,
      }
      if (config.onDownProduce === 'notification') tools.produce.notification(msg_data)
      else tools.produce.alarm(msg_data)
    }

    /*
     * Update the cache
     */
    if (config.cache) tools.cache.healthcheck(data, { time, up, ms, dbce })

    /*
     * Can't do a simple if (!dbce) here because dbce can be zero
     */
    if (dbce !== undefined) {
      // FIXME: Make this treshold configurable
      if (dbce < 5) tools.produce.alarm({
        context: tools.create.context(`tls.certificate.${tools.format.escape(data.url.full)}`),
        host: data?.url?.domain,
        module: data?.morio?.module?.name,
        title: `⏳ Certificate will expire in ${dbce} days: ${data?.url?.full}`,
        type: 'tls.certificate.expiry.imminent',
        tags: ['tls','certificate','expiry'],
      })
      // FIXME: Make this treshold configurable
      else if (dbce < 15) tools.produce.notification({
        context: tools.create.context(`tls.certificate.${tools.format.escape(data.url.full)}`),
        host: data?.url?.domain,
        module: data?.morio?.module?.name,
        tags: ['tls','certificate','expiry'],
        title: `⏳ Certificate will expire in ${dbce} days: ${data?.url?.full}`,
        type: 'tls.certificate.expiry.approaching',
      })
    }
  }
}

export default handler

/*
 * Takes healthcheck data and returns and array with the key observations
 *
 * @param {object} data - The healthcheck data
 * @return {array} summary - An array holding:
 *   - up (1 or 0)
 *   - the ms it took to complete the healthcheck
 *   - days until the certificate expires
 */
function healthcheckSummary (data, tools) {
  return [
    (config.upValues.indexOf(data.monitor.status.toLowerCase()) !== -1) ? 1 : 0,
    Math.ceil(data.monitor.duration.us/1000),
    (config.checkCertificates && data.monitor.type === 'http' && data.tls && data.url?.scheme === 'https')
      ? checkCertificateExpiry(data, tools)
      : undefined
  ]
}

/*
 * Checks certificate validity
 *
 * @param {object} data - The healthcheck data
 */
const checkCertificateExpiry = (data, tools) => {
  const seconds = Math.floor(
    (new Date(data.tls.certificate_not_valid_after).getTime()/1000)
    - tools.time.now()
  )

  return Math.floor(seconds / (24 * 3600))
}
