import { ensureServiceCertificate } from '#lib/tls'
import { utils, log } from '../utils.mjs'
import { chown, mkdir, readFile, writeFile } from '#shared/fs'
// Default hooks
import { defaultRestartServiceHook, defaultRecreateServiceHook } from './index.mjs'

/**
 * Service object holds the various lifecycle methods
 */
export const service = {
  name: 'eda',
  hooks: {
    /*
     * Lifecycle hook to determine the service status (runs every heartbeat)
     */
    heartbeat: async () => {
      if (!utils.getFlag('ENABLE_SERVICE_EDA', false)) return true

      // FIXME
      return false
    },
    /*
     * Lifecycle hook to determine whether the container is wanted
     * The EDA service needs to be enabled with a feature flag
     */
    wanted: () => utils.getFlag('ENABLE_SERVICE_EDA', false),
    /**
     * Lifecycle hook for anything to be done prior to creating the container
     */
    precreate: ensureLocalPrerequisites,
    /**
     * Lifecycle hook for anything to be done prior to starting the container
     *
     * @return {boolean} success - Indicates lifecycle hook success
     */
    prestart: async () => await ensureServiceCertificate('eda', true),
    /*
     * Lifecycle hook to determine whether to recreate the service
     * We just reuse the default hook here, telling it we need TLS configured.
     */
    recreate: () => {
      ensureLocalPrerequisites()
      return defaultRecreateServiceHook('eda')
    },
    /**
     * Lifecycle hook to determine whether to restart the service
     * We just reuse the default hook here, checking whether the service
     * was recreated or is not running.
     */
    restart: (hookParams) => defaultRestartServiceHook('eda', hookParams),
  },
}

async function ensureLocalPrerequisites() {
  try {
    // Create config folder
    await mkdir('/etc/morio/eda')
    await chown('/etc/morio/eda', 1000, 1000)

    // Create data folder
    await mkdir('/morio/data/eda')
    await chown('/morio/data/eda', 1000, 1000)

    // Write Node-RED settings file
    await writeFile(
      '/etc/morio/eda/settings.js',
      [
        `// Node-RED settings auto-generated by Morio`,
        `module.exports = ${JSON.stringify(utils.getMorioServiceConfig('eda').eda, null, 2)}`,
      ].join('\n'),
      log,
      0o640
    )
    // Prevent read access
    await chown('/etc/morio/eda/settings.js', 1000, 1000)

    // Ensure service certificate exists
    await ensureServiceCertificate('eda', true)

    // Construct Morio plugin settings
    const settings = {
      broker: {
        brokers: utils.getBrokerFqdns().map((broker) => `${broker}:9092`),
        clientId: 'morio-eda',
        logLevel: 'debug',
        ssl: {
          rejectUnauthorized: false,
          ca: [await readFile(`/etc/morio/eda/tls-cert.pem`)],
          cert: await readFile(`/etc/morio/eda/tls-cert.pem`),
          key: await readFile(`/etc/morio/eda/tls-key.pem`),
        },
      },
      consumer: {},
      producer: {},
    }

    // Write Morio plugin settings file
    await writeFile(
      '/etc/morio/eda/morio-settings.js',
      [
        `// These settings are auto-generated by Morio`,
        `module.exports = ${JSON.stringify(settings, null, 2)}`,
      ].join('\n'),
      log,
      0o640
    )
    // Prevent read access
    await chown('/etc/morio/eda/morio-settings.js', 1000, 1000)
  } catch (err) {
    log.warn(err, `Precreate hook failed for EDA service`)
  }

  return true
}
