import { readFile, writeFile } from '#shared/fs'
import { ensureServiceCertificate } from '#lib/tls'
// Default hooks
import {
  defaultRecreateServiceHook,
  defaultRestartServiceHook,
  defaultServiceWantedHook,
} from './index.mjs'
// log & utils
import { log, utils } from '../utils.mjs'

/**
 * Service object holds the various lifecycle hook methods
 */
export const service = {
  name: 'tap',
  hooks: {
    /**
     * Lifecycle hook to determine whether the container is wanted
     *
     * @return {boolean} wanted - Wanted or not
     */
    wanted: () => {
      ensureLocalPrerequisites()
      return defaultServiceWantedHook
    },
    /*
     * Lifecycle hook to determine whether to recreate the container
     * We just reuse the default hook here, checking for changes in
     * name/version of the container.
     */
    recreate: () => defaultRecreateServiceHook('tap'),
    /**
     * Lifecycle hook to determine whether to restart the container
     * We just reuse the default hook here, checking whether the container
     * was recreated or is not running.
     */
    restart: (hookParams) => defaultRestartServiceHook('tap', hookParams),
    /**
     * Lifecycle hook for anything to be done prior to creating the container
     *
     * Write out the heartbeat.yml file as it will be volume-mapped,
     * so we need to write it to disk first so it's available
     */
    precreate: ensureLocalPrerequisites,
  },
}

async function ensureLocalPrerequisites() {
  log.todo('Ensureing tap')
  /*
   * Generate key and certificate for mTLS
   */
  await ensureServiceCertificate('tap', false)

  /*
   * Copy key and certificates into mounted folder
   */
  //for (const file of ['tls-ca.pem', 'tls-cert.pem', 'tls-key.pem'])
  //  await cp(`/etc/morio/tap/${file}`, `/etc/morio/watcher/tls/${file}`)

  /*
   * Write  the tap config file
   */
  const config = {
    clientId: 'morio-tap',
    brokers: [`${utils.getNodeFqdn()}:${utils.getPreset('MORIO_BROKER_KAFKA_API_EXTERNAL_PORT')}`],
    ssl: {
      rejectUnauthorized: false,
      ca: [await readFile('/etc/morio/tap/tls-ca.pem')],
      key: await readFile('/etc/morio/tap/tls-key.pem'),
      cert: await readFile('/etc/morio/tap/tls-cert.pem'),
    },
  }
  await writeFile(
    `/etc/morio/tap/tap.mjs`,
    '// This file is auto-generated by Morio Core\nconst config = ' +
      JSON.stringify(config, null, 2) +
      '\nexport default config\n'
  )

  return true
}
