/*
 * This file is auto-generated by Morio Core
 * Any manual changes will be overwritten
 */

// Tap config for builting handler audit
export const config = {
  "enabled": true,
  "topics": {
    "audit": "audit"
  },
  "modules": {},
  "cache": true,
  "ttl": 12,
  "eventify": true
}
