/*
 * This file is auto-generated by Morio Core
 * Any manual changes will be overwritten
 */

// Tap config for builting handler logs
export const config = {
  "enabled": true,
  "topics": {
    "logs": "logs"
  },
  "modules": {},
  "cache": true,
  "ttl": 1
}
