/*
 * This file is auto-generated by Morio Core
 * Any manual changes will be overwritten
 */

// Tap config for builting handler healthchecks
export const config = {
  "enabled": true,
  "topics": {
    "checks": "checks"
  },
  "modules": {},
  "cache": true,
  "ttl": 1,
  "up_values": {
    "1": 1,
    "green": "green",
    "up": "up"
  },
  "on_down": "event",
  "certificate_check": true,
  "certificate_notification_days": 15,
  "certificate_alarm_days": 5,
  "certificate_event_days": 16
}
