- package-ecosystem: npm
  directory: '/'
  assignees: &ass
    - joostdecock
  commit-message: &msg
    prefix: '[deps]'
    prefix-development: '[dev-devps]'
  open-pull-requests-limit: &limit 25
  schedule.interval: &interval weekly

- package-ecosystem: npm
  directory: '/api'
  assignees: *ass
  commit-message: *msg
  open-pull-requests-limit: *limit
  schedule.interval: *interval

- package-ecosystem: npm
  directory: '/defaults'
  assignees: *ass
  commit-message: *msg
  open-pull-requests-limit: *limit
  schedule.interval: *interval

- package-ecosystem: npm
  directory: '/sam'
  assignees: *ass
  commit-message: *msg
  open-pull-requests-limit: *limit
  schedule.interval: *interval

- package-ecosystem: npm
  directory: '/schema'
  assignees: *ass
  commit-message: *msg
  open-pull-requests-limit: *limit
  schedule.interval: *interval

- package-ecosystem: npm
  directory: '/shared'
  assignees: *ass
  commit-message: *msg
  open-pull-requests-limit: *limit
  schedule.interval: *interval

- package-ecosystem: npm
  directory: '/ui'
  assignees: *ass
  commit-message: *msg
  open-pull-requests-limit: *limit
  schedule.interval: *interval
