- package-ecosystem: npm
  directory: "/"
  schedule: *schedule
  assignees: *assignees
    - "joostdecock"
  interval: "weekly"
  commit-message: *commit
    prefix: "[dependencies]"
    prefix-development: "[dev-dependencies]"
  open-pull-requests-limit: &limit 25
- package-ecosystem: npm
  directory: "/api"
  schedule: &schedule
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: *limit
- package-ecosystem: npm
  directory: "/defaults"
  schedule: &schedule
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: *limit
- package-ecosystem: npm
  directory: "/sam"
  schedule: &schedule
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: *limit
- package-ecosystem: npm
  directory: "/schema"
  schedule: &schedule
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: *limit
- package-ecosystem: npm
  directory: "/shared"
  schedule: &schedule
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: *limit
- package-ecosystem: npm
  directory: "/ui"
  schedule: &schedule
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: *limit

