- package-ecosystem: npm
  directory: "/"
  assignees: *assignees
    - "joostdecock"
  commit-message: *commit
    prefix: "[deps]"
    prefix-development: "[dev-devps]"
  open-pull-requests-limit: *limit 25
  schedule: *schedule
    interval: "weekly"

- package-ecosystem: npm
  directory: "/api"
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: &limit
  schedule: &schedule

- package-ecosystem: npm
  directory: "/defaults"
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: &limit
  schedule: &schedule

- package-ecosystem: npm
  directory: "/sam"
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: &limit
  schedule: &schedule

- package-ecosystem: npm
  directory: "/schema"
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: &limit
  schedule: &schedule

- package-ecosystem: npm
  directory: "/shared"
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: &limit
  schedule: &schedule

- package-ecosystem: npm
  directory: "/ui"
  assignees: &assignees
  commit-message: &commit
  open-pull-requests-limit: &limit
  schedule: &schedule

