#!/bin/bash
# This restarts all Morio (client) services

# Check for systemd
which systemctl 2> /dev/null
if [ $? -eq 0 ]
then
  systemctl restart morio-audit
  systemctl restart morio-logs
  systemctl restart morio-metrics
else
  /etc/init.d/morio-audit restart
  /etc/init.d/morio-logs restart
  /etc/init.d/morio-metrics restart
fi
exit 0
