#!/bin/bash
# This stops all Morio (client) services

# Check for systemd
which systemctl 2> /dev/null
if [ $? -eq 0 ]
then
  systemctl stop morio-audit
  systemctl stop morio-logs
  systemctl stop morio-metrics
else
  /etc/init.d/morio-audit stop
  /etc/init.d/morrio-logs stop
  /etc/init.d/morio-metrics stop
fi
exit 0
