#!/bin/bash
# This starts all morio (client) services

# Check for systemd
which systemctl 2> /dev/null
if [ $? -eq 0 ]
then
  systemctl start morio-audit
  systemctl start morio-logs
  systemctl start morio-metrics
else
  /etc/init.d/morio-audit start
  /etc/init.d/morio-logs start
  /etc/init.d/morio-metrics start
fi
exit 0
