/*
 * This file is auto-generated by Morio Core
 * Any manual changes will be overwritten
 */

// Tap config for builting handler inventory
export const config = {
  "handlers": {
    "metrics": {
      "enabled": true,
      "name": "metrics",
      "topic": "metrics"
    },
    "inventory": {
      "name": "inventory",
      "topic": "inventory",
      "enabled": true,
      "filter": false
    }
  }
}
