#!/bin/bash
# Post-Install script for morio-client

# Bail on all errors
set -e

# Reload systemd
systemctl daemon-reload || true

# Configure services
/usr/sbin/morio init
systemctl enable morio-audit
systemctl enable morio-logs
systemctl enable morio-metrics

