#!/bin/bash
# Post-Install script for morio-client

# Bail on all errors
set -e

# Reload systemd
systemctl daemon-reload || true

# Configure services
/usr/sbin/morio template
systemctl enable morio-audit
systemctl enable morio-logs
systemctl enable morio-metrics
systemctl restart morio-audit || true
systemctl restart morio-logs || true
systemctl restart morio-metrics || true

