# This holds the configuration wizard view settings for the Morio specific
# config Morio-specific means it's not about how to configure individual
# components, but rather about how everything should work together
about: |
  The Morio core configuration holds the most foundational settings of your Morio setup.
  Without a core configuration, Morio cannot function.
title: Morio Core
type: info
next: morio.cluster
children:
  # First thing to do is figure out how many nodes we should deploy
  node_count:
    # This configId value (or the key for other blocks) determines where the data will be
    # stored in the configuration (in this case under morio.node_count)
    configId: morio.node_count
    # Wizard view to go to next
    next: morio.nodes
    type: list
    title: Node vs Cluster
    input:
      - val: 1
        label: Morio Node
        about: |
          - Setup a standalone Morio node
          - Recommended for small deployments
          - Provides a simpler setup with less moving parts
      - val: 3
        label: Morio Cluster
        about: |
          - Setup a 3-node Morio cluster
          - Recommended for larger deployments
          - Provides high availibility and horizontal scaling
      - label: Larger Morio cluster sizes
        about: |
          - Setup a larger Morio cluster
          - Recommended for increased throughput
          - Size matters, but bigger is not always better
        hide: Show larger Morio cluster sizes
        val:
          type: select
          values: [5, 7, 9, 11, 13, 15]
          labels:
            - 5 nodes
            - 7 nodes
            - 9 nodes
            - 11 nodes
            - 13 nodes
            - 15 nodes
          label: Cluster nodes
          about: Choose the amount of nodes in the Morio cluster

  # Next thing we need is the names of the nodes
  nodes:
    type: strings
    count: '{{ CONFIG.morio.node_count }}'
    label: Nodes
    labels: 'Node {{ INDEX_PLUS_ONE }}'
    labelsTR: 'Enter the fully qualified domain name of node {{ INDEX_PLUS_ONE }}'
    about: Each Morio nodes needs a name that will resolve in DNS (an FQDN)
    placeholder: host.my.domain.com
    next: morio.display_name

  # We also like a display name to refer to Morio as a whole
  # Allowing for something more user-friendly, or differentating between different environments
  display_name:
    type: string
    label: Display Name
    about: A human-friendly name to refer to this Morio setup
    placeholder: Morio Production
    next:
      if:
        val: '{{ CONFIG.morio.node_count }}'
        as: number
      is: 1
      then: validate
      else: morio.cluster_name

  # For clusters, we also suggest/want/need a round-robin DNS address
  cluster_name:
    type: string
    label: Cluster Name
    about: |
      A round-robin DNS record for the entire Morio cluster. 
      This should resolve the the IP addresses of all cluster nodes.
    placeholder: cluster.my.domain.com
    next: morio.leader_ip
    hide:
      if:
        val: '{{ CONFIG.morio.node_count }}'
        as: number
      is: 1

  # For clusters, we also suggest/want/need a round-robin DNS address
  leader_ip:
    type: string
    label: Leader IP Address
    about: |
      In addition to the name, we need the IP address of the leader node (this node).
    placeholder: 10.0.0.1
    suggest:
      macro: validateNode
      label: Use this value?
      about: |
        We attempted to determine the IP address of a potential leader node.
        If this is the correct IP, you can accept this suggestion.
        Or, if you like you can enter an IP address manually.
    next: validate
    hide:
      if:
        val: '{{ CONFIG.morio.node_count }}'
        as: number
      is: 1
