container:
  image: smallstep/step-ca
  tag: 0.25.2
  name: ca
  network: morio-net
  ports: []
  volumes:
    - 'MORIO_ROOT/data/ca:/home/step'
  env:
    DOCKER_STEPCA_INIT_NAME: MORIO_DISPLAY_NAME
    DOCKER_STEPCA_INIT_DNS_NAMES: "localhost,engn-vm2.cert.europa.eu,ca.cert.europa.eu"

