## Stage 1: Build in NodeJS v20 (builder)
FROM node:20-slim as builder

## Make this folder our working directory
WORKDIR /morio/core

## Set environment variable to indicate this is production code
ENV NODE_ENV production

## Install dependencies, build and debug tools,  and updates
RUN apt-get update && apt-get install -y git python3 make g++ vim curl netcat-openbsd && apt-get upgrade -y

## Copy in source and config
COPY . .

## Install/Build the depdendencies that have native bindings
RUN npm install ssh2 cpu-features

## Install the pm2 process manager for NodeJS
RUN npm install pm2 -g

## Install all dependencies
RUN npm i

## Copy the various PM2 scripts into the PATH
COPY bin/* /usr/local/bin/

## Copy the PM2 config file
COPY pm2.canary.config.js /morio/core/pm2.config.js

## Now run NodeJS code inside PM2
CMD [ "pm2-runtime", "start", "/morio/core/pm2.config.js" ]
