/*
 * This file was auto-generated by the prebuild script
 * Any changes you make to it will be lost on the next (pre)build.
 */
export const docsNavs = {
  docs: {
    t: 'Documentation',
    o: 'Documentation',
    about: {
      t: 'About Morio',
      o: 'About Morio',
      nodes: { t: 'Morio Nodes', o: 'Morio Nodes' },
      services: {
        t: 'Morio Services',
        o: 'Morio Services',
        api: { t: 'Operator API', o: 'Operator API' },
        ca: { t: 'Certificate Authority', o: 'Certificate Authority' },
        console: { t: 'Broker Console', o: 'Broker Console' },
        core: { t: 'Core', o: 'Core' },
        ingest: { t: 'Ingest API', o: 'Ingest API' },
        kafka: { t: 'Kafka API', o: 'Kafka API' },
        proxy: { t: 'Proxy', o: 'Proxy' },
        ui: { t: 'Web Interface', o: 'Web Interface' },
      },
    },
    faq: {
      t: 'Frequently Asked Questions',
      o: 'Frequently Asked Questions',
      ca: {
        t: 'Certificate Authority',
        o: 'Certificate Authority',
        'can-you-trust-the-ca': {
          t: 'Can you trust the internal Morio Certificate Authority?',
          o: 'Can you trust the internal Morio Certificate Authority?',
        },
        'how-to-trust-the-ca': {
          t: 'How can you establish trust for the internal Morio Certificate Authority?',
          o: 'How can you establish trust for the internal Morio Certificate Authority?',
        },
      },
    },
    reference: {
      t: 'Reference',
      o: '10Reference',
      rbac: { t: 'RBAC', o: 'RBAC' },
      terminology: {
        t: 'Terminology',
        o: 'Terminology',
        ca: { t: 'CA', o: 'CA' },
        dry: { t: 'DRY', o: 'DRY' },
        tls: { t: 'TLS', o: 'TLS' },
        x509: { t: 'X.509', o: 'X.509' },
      },
    },
  },
}
