/*
 * This file was auto-generated by the prebuild script
 * Any changes you make to it will be lost on the next (pre)build.
 */
import * as ca from 'pages/docs/reference/terminology/ca.mdx'
import * as dry from 'pages/docs/reference/terminology/dry.mdx'
import * as tls from 'pages/docs/reference/terminology/tls.mdx'
import * as x509 from 'pages/docs/reference/terminology/x509.mdx'

export const terminology = {
  ca,
  dry,
  tls,
  x509,
}
