import { config } from "./config.mjs"

// Make this an array
config.up_values = Object.values(config.up_values)

/*
 * This is a Morio handler to process healthchecks data generated by the Morio
 * Watcher service.
 *
 * It can create a notification (or alarm) when something is down, and will
 * also cache the healthcheck data for dashboarding, as well as verify the
 * expiry date of any TLS certificates.
 *
 * It will set cache keys as such:
 *  - check|[full healthcheck url] eg: https://morio-ca:9000/health* : Holds a sorted set (ZSET) with healthcheck data
 *  - checks : Holds the list of healthcheck keys
 *
 */
const handler = config.enabled ? {
  ...config,
  method: (data, tools, topic) => {
    /*
     * Only handle data that is in the correct format
     */
    if (!data?.monitor?.id || !data?.monitor?.name) return tools.note('Invalid healthcheck data', data)

    if (!data.url?.full) return tools.cache.note(`Healtcheck has no full URL`, data)

    /*
     * Summarize the healthcheck for the cache
     */
    const summary = healthcheckSummary(data, tools)

    /*
     * Update the cache
     */
    if (config.cache) tools.cache.healthcheck(summary, data, config)

    return
    /*
     * Escalate if needed
     */
    if (!summary.up && ['alarm', 'notification'].includes(config.on_down_produce)) {
      // Prepare the nessage data
      const msg_data = {
        context: tools.create.context('healthcheck', data.monitor.type, data.monitor.id, tools.format.escape(data.url?.full)),
        host: data.host?.id,
        module: data.morio?.module?.name,
        tags: [ 'healthcheck', 'down', data.monitor.type, data.monitor.id ],
        time,
        title: `Healthcheck failed: ${data.url?.full}`,
        type: `${data.monitor.type}.healthcheck.down`,
      }
      if (config.on_down_produce === 'notification') tools.produce.notification(msg_data)
      else tools.produce.alarm(msg_data)
    }

    /*
     * Can't do a simple if (!dbce) here because dbce can be zero
     */
    if (dbce !== undefined) {
      if (dbce < config.certificate_expires_days_alarm) tools.produce.alarm({
        context: tools.create.context(`tls.certificate.${tools.format.escape(data.url.full)}`),
        host: data?.url?.domain,
        module: data?.morio?.module?.name,
        title: `⏳ Certificate will expire in ${dbce} days: ${data?.url?.full}`,
        type: 'tls.certificate.expiry.imminent',
        tags: ['tls','certificate','expiry'],
      })
      else if (dbce < config.certificate_expires_days_notify) tools.produce.notification({
        context: tools.create.context(`tls.certificate.${tools.format.escape(data.url.full)}`),
        host: data?.url?.domain,
        module: data?.morio?.module?.name,
        tags: ['tls','certificate','expiry'],
        title: `⏳ Certificate will expire in ${dbce} days: ${data?.url?.full}`,
        type: 'tls.certificate.expiry.approaching',
      })
    }
  }
} : false

export default handler

/*
 * Takes healthcheck data and returns and array with the key observations
 *
 * @param {object} data - The healthcheck data
 * @return {array} summary - An array holding:
 *   - up (1 or 0)
 *   - the ms it took to complete the healthcheck
 *   - days until the certificate expires
 */
function healthcheckSummary (data, tools) {
  return {
    // Up or not?
    up: (config.up_values.indexOf(data.monitor.status.toLowerCase()) !== -1) ? 1 : 0,
    // Milliseconds the healthcheck took
    ms: Math.ceil(data.monitor.duration.us/1000),
    // Days before certificate expiry
    dbce: (config.check_certificate && data.monitor.type === 'http' && data.tls && data.url?.scheme === 'https')
      ? checkCertificateExpiry(data, tools)
      : undefined,
    // Uptime from historic healthchecks
    uptime: data.state.up / data.state.checks,
    // Start of the historic healthchecks
    uptime_since: data.state.started_at,
    // Time of this specific healthcheck
    time: tools.time.when(data),
    // Type of healthcheck
    type: data.monitor.type,
    // ID of the healthcheck
    id: data.monitor.id,
    // Name of the healthcheck
    name: data.monitor.name,
    // URL of the healthcheck
    url: data.url.full,
    /*
     * Name/ID of the agent
     * This helps us differentiate when running the same healthcheck from 2 places
     * Something tha tis very useful when your infra spans multiple sites
     */
    from: data.agent.name || agent.id,
  }
}

/*
 * Checks certificate validity
 *
 * @param {object} data - The healthcheck data
 */
const checkCertificateExpiry = (data, tools) => {
  const seconds = Math.floor(
    (new Date(data.tls.certificate_not_valid_after).getTime()/1000)
    - tools.time.now()
  )

  return Math.floor(seconds / (24 * 3600))
}
