import { config } from "./config.mjs"

// Make this an array
config.up_values = Object.values(config.up_values)

/*
 * This is a Morio handler to process healthchecks data generated by the Morio
 * Watcher service.
 *
 * It can create a notification (or alarm) when something is down, and will
 * also cache the healthcheck data for dashboarding, as well as verify the
 * expiry date of any TLS certificates.
 *
 * It will set cache keys as such:
 *  - check|[full healthcheck url] eg: https://morio-ca:9000/health* : Holds a sorted set (ZSET) with healthcheck data
 *  - checks : Holds the list of healthcheck keys
 *
 */
const handler = config.enabled ? {
  ...config,
  method: (data, tools, topic) => {
    /*
     * Only handle data that is in the correct format
     */
    if (!data?.monitor?.id || !data?.monitor?.name) return tools.note('Invalid healthcheck data', data)

    if (!data.url?.full) return tools.cache.note(`Healtcheck has no full URL`, data)

    /*
     * Summarize the healthcheck for the cache
     */
    const summary = healthcheckSummary(data, tools)

    /*
     * Update the cache
     */
    if (config.cache) tools.cache.healthcheck(summary, data, config)

    /*
     * Escalate if needed
     */
    if (!summary.up && config.escalate_when_down) tools.produce.event({
      context: tools.create.context('check', summary.id, summary.from),
      href: `https://${tools.node.cluster}/boards/checks/${summary.id}`,
      time: summary.time,
      title: `Health check failed: ${summary.name}`,
      type: `${summary.type}.healthcheck.down`,
      data: {
        from: summary.from,
        id: summary.id,
        type: summary.type,
      },
    })

    /*
     * Can't do a simple if (!dbce) here because dbce can be zero
     */
    if (summary.dbce !== undefined) {
      const { certificate_days = 21 } = config
      if (summary.dbce < certificate_days) tools.produce.event({
        context: tools.create.context(`tls.certificate.${tools.format.escape(data.url.full)}`),
        href: `https://${tools.node.cluster}/boards/checks/${summary.id}`,
        title: `⏳ Certificate will expire in ${summary.dbce} days: ${data?.url?.full}`,
        time: summary.time,
        type: 'tls.certificate.expiry',
        data: { days_before_expiry: summary.dbce }
      })
    }
  }
} : false

export default handler

/*
 * Takes healthcheck data and returns and array with the key observations
 *
 * @param {object} data - The healthcheck data
 * @return {array} summary - An array holding:
 *   - up (1 or 0)
 *   - the ms it took to complete the healthcheck
 *   - days until the certificate expires
 */
function healthcheckSummary (data, tools) {
  return {
    // Up or not?
    up: (config.up_values.indexOf(data.monitor.status.toLowerCase()) !== -1) ? 1 : 0,
    // Milliseconds the healthcheck took
    ms: Math.ceil(data.monitor.duration.us/1000),
    // Days before certificate expiry
    dbce: (config.certificate_check && data.monitor.type === 'http' && data.tls && data.url?.scheme === 'https')
      ? checkCertificateExpiry(data, tools)
      : undefined,
    // Uptime from historic healthchecks
    uptime: data.state.up / data.state.checks,
    // Start of the historic healthchecks
    uptime_since: data.state.started_at,
    // Time of this specific healthcheck
    time: tools.time.when(data),
    // Type of healthcheck
    type: data.monitor.type,
    // ID of the healthcheck
    id: data.monitor.id,
    // Name of the healthcheck
    name: data.monitor.name,
    // URL of the healthcheck
    url: data.url.full,
    /*
     * Name/ID of the agent
     * This helps us differentiate when running the same healthcheck from 2 places
     * Something tha tis very useful when your infra spans multiple sites
     */
    from: data.agent.name || agent.id,
  }
}

/*
 * Checks certificate validity
 *
 * @param {object} data - The healthcheck data
 */
const checkCertificateExpiry = (data, tools) => {
  const seconds = Math.floor(
    (new Date(data.tls.certificate_not_valid_after).getTime())
    - tools.time.now()
  )
  tools.note('cert check', {
    seconds,
    exp: data.tls.certificate_not_valid_after
  })

  return Math.floor(seconds / (24 * 3600))
}
