# Target-specific configuration
targets:
  production:
    # The image to run in production
    # The specific tag will be added by the reconfigure script
    image: morio/api
  development:
    # The image to run in development
    # The specific tag will be added by the reconfigure script
    image: morio/api-dev
    volumes:
      - '{{{ MORIO_REPO_ROOT }}}:/morio'

container:
  # Name it api
  container_name: morio_api
  # Tag will be injected
  tag: '{{{ MORIO_VERSION }}}'
  # Use the default network
  networks:
    default: null
  # Run an init inside the container to forward signales (and avoid PID 1)
  init: true
  # Configure Traefik with container labels
  labels:
    # Tell traefik to watch this container
    - traefik.enable=true
    # Attach to the morio_net network
    - traefik.docker.network=morio_net
    # Match requests going to the API prefix (triple curly braces are required here)
    - traefik.http.routers.morio_api.rule=PathPrefix(`{{{ MORIO_API_PREFIX }}}`)
    # Set priority to avoid rule conflicts
    - traefik.http.routers.morio_api.priority=100
    # Forward to api service
    - traefik.http.routers.morio_api.service=morio_api
    # Only match requests on the https endpoint
    - traefik.http.routers.morio_api.entrypoints=https
    # Forward to port on container
    - 'traefik.http.services.morio_api.loadbalancer.server.port={{ MORIO_API_PORT }}'
    # Enable TLS
    - traefik.http.routers.morio_api.tls=true
