container:
  image: smallstep/step-ca
  tag: 0.25.2
  container_name: morio_ca
  network: morio_net
  ports: 
    - 9000:9000
  volumes:
    - '{{{ MORIO_REPO_ROOT }}}/data/ca:/home/step'
  environment:
    #DOCKER_STEPCA_INIT_NAME: '{{{ MORIO_CA_NAME }}}'
    #DOCKER_STEPCA_INIT_DNS_NAMES: 'localhost,{{{ MORIO_DNS_NAMES }}}'
  # Configure Traefik with container labels
  labels:
    # Tell traefik to watch this container
    - traefik.enable=true
    # Attach to the morio_net network
    - traefik.docker.network=morio_net
    # Match requests going to the CA root certificate
    - traefik.http.routers.morio_ca.rule=PathPrefix(`/roots.pem`)
    # Set priority to avoid rule conflicts
    - traefik.http.routers.morio_ca.priority=120
    # Forward to the CA api
    - traefik.http.routers.morio_ca.service=morio_ca
    # Only match requests on the https endpoint
    - traefik.http.routers.morio_ca.entrypoints=https
    # Forward to port on container
    - traefik.http.services.morio_ca.loadbalancer.server.port=9000
    # Enable TLS
    - traefik.http.routers.morio_ca.tls=true

server:
  root: /home/step/certs/root_ca.crt
  federatedRoots: null
  crt: /home/step/certs/intermediate_ca.crt
  key: /home/step/secrets/intermediate_ca_key
  address: ":9000"
  insecureAddress: ""
  dnsNames:
    - localhost
    - morio_ca
  logger:
    format: json
  db:
    type: badgerv2
    dataSource: /home/step/db
  clr:
    enabled: false
  authority:
    claims:
      minTLSCertDuration: 5m
      maxTLSCertDuration: 17544h
      defaultTLSCertDuration: 750h
      disableRenewal: false
      allowRenewalAfterExpiry: true
    provisioners:
      - type: JWK
        name: admin
        key: null
        encryptedKey: null
  tls:
    cipherSuites:
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    minVersion: 1.2
    maxVersion: 1.3
    renegotiation: false

client:
  ca-url: 'https://localhost:9000'
  ca-config: '/home/step/config/ca.json'
  fingerprint: to-be-set-by-core
  root: /home/step/certs/root_ca.crt
