container:
  image: 'traefik:2.10.7'
  container_name: morio_traefik
  command:
    - traefik
    # Enable the Traefik API (required for dashboard) and Dashboard
    - '--api=true'
    - '--api.dashboard=true'
    # Use Docker as provider
    - '--providers.docker=true'
    # Only export containers when we explicitly configure it
    - '--providers.docker.exposedbydefault=false'
    # Create HTTP entrypoint (only to redirect to HTTPS)
    - '--entrypoints.http.address=:80'
    # Always redirect all HTTP requests to HTTPS
    - '--entrypoints.http.http.redirections.entrypoint.to=https'
    - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
    - '--entrypoints.http.http.redirections.entrypoint.permanent=true'
    #  Create HTTPS entrypoint
    - '--entrypoints.https.address=:443'
    # Set the log level
    - '--log.level={{ MORIO_TRAEFIK_LOG_LEVEL }}'
    # Set the log destination
    - '--log.filePath={{{ MORIO_TRAEFIK_LOG_FILEPATH }}}'
    # Set the log format
    - '--log.format={{ MORIO_TRAEFIK_LOG_FORMAT }}'
    # Enable access logs
    - '--accesslog=true'
    # Set the access log destination
    - '--accesslog.filePath={{{ MORIO_TRAEFIK_ACCESS_LOG_FILEPATH }}}'
    # Do not verify backend certificates, just encrypt
    - '--serversTransport.insecureSkipVerify=true'

  labels:
    # Tell traefik to watch itself (so meta)
    - traefik.enable=true
    # Attach to the morio_net network
    - traefik.docker.network=morio_net
    # Match rule for Traefik's internal dashboard
    - 'traefik.http.routers.traefik_dashboard.rule=(PathPrefix(`/api/`) || PathPrefix(`/dashboard/`))'
    # Avoid rule conflicts by setting priority manually
    - 'traefik.http.routers.traefik_dashboard.priority=199'
    # Route it to Traefik's internal API
    - 'traefik.http.routers.traefik_dashboard.service=api@internal'
    # Enable TLS
    - 'traefik.http.routers.traefik_dashboard.tls=true'
    # Only listen on the https endpoint
    - traefik.http.routers.traefik_dashboard.entrypoints=https
  networks:
    default: null
  ports:
    - 80:80
    - 443:443
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - '{{{ MORIO_REPO_ROOT }}}/logs/:/var/log/morio/'
