container:
  image: 'traefik:2.10.7'
  container_name: traefik
  command:
    - '--api.insecure=true'
    - '--providers.docker'
    - '--providers.docker.exposedbydefault=false'
    - '--entrypoints.web.address=:80'
  networks:
    default: null
  ports:
    - 80:80
    - 8080:8080
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
