#!/bin/bash
# Post-Install script for moriod

set -e

# Reload systemd
systemctl daemon-reload || true

# Enable services
systemctl enable docker || true
systemctl enable moriod || true

# Start services
systemctl start docker || true
systemctl start moriod || true

