version: '3.3'
name: morio
services:
  api:
    image: morio/api:0.1.0
    container_name: api
    networks:
      default: null
  sam:
    image: morio/sam:0.1.0
    container_name: sam
    networks:
      default: null
  traefik:
    image: traefik:2.10.7
    container_name: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    networks:
      default: null
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    name: morio_net
