/*
 * Configuration for the morio_logs_cache handler
 */
export const config = {
  enabled: true,
  handler: {
    topic: 'logs',
    filter: false,
  },
  cap: 30, // 30 most recent lines
  ttl: 86400, // 24 hours
}

export const docs = {
  name: 'Morio Logs Cache Handler',
  description: `
This stream processing handler processes Morio healthchecks, which under the hood are generated by Elastic Heartbeat.

It will validate the healthcheck, and can produce a notification in case the healthcheck fails.
It can also check certificate expiry and cache the healthcheck results for dashboarding.

This handler can be further configured to control its behaviour.`,
  config: {
    enabled: "Set this to false to disable this handler.",
    cap: "The maximum number of entries to keep in the cache for this logset",
    ttl: "The time before the logset key will expire. Log sets that see no updates during this time span will be dropped from the cache.",
  }
}

