## Run in Debian 12 (bookworm)
FROM debian:12

# Make this folder our working directory
WORKDIR /morio

## Install aptly and all the latest updates
RUN apt update && apt install -y aptly gpg && apt upgrade -y

# Add aptly config
COPY ./aptly.conf /root/.aptly.conf

# Add builder script as custom entrypoint
COPY ./entrypoint.sh /entrypoint.sh

## Run the builder script
CMD ["/entrypoint.sh"]
