/*
 * Configuration for the morio_logs_cache handler
 */
export const config = {
  enabled: true,
  handler: {
    topic: 'logs',
    filter: false,
  },
  cache_lines: 30, // 30 most recent lines
  expire_seconds: 86400, // 24 hours
}

export const docs = {
  name: 'Morio Logs Cache Handler',
  description: `
This stream processing handler processes Morio healthchecks, which under the hood are generated by Elastic Heartbeat.

It will validate the healthcheck, and can produce a notification in case the healthcheck fails.
It can also check certificate expiry and cache the healthcheck results for dashboarding.

This handler can be further configured to control its behaviour.`,
  config: {
    enabled: "Set this to false to disable this handler.",
    cache_lines: "The number of most recent loglines to keep in the cache",
    expire_seconds: "The time before the log key will expire. Log files that see no updates during this time span will be dropped from the cache.",
  }
}

