/*
 * Configuration for the morio_watcher_healthchecks handler
 */
export const config = {
  enabled: true,
  handler: {
    topic: 'checks',
    filter: false,
  },
  cache: true,
  ttl: 3600, // 1 hour of healtcheck data
  check_certificate: true,
  certificate_expires_days_notify: 5,
  certificate_expires_days_alarm: 15,
  on_down: 'notification',
  up_values: [ "1", "up", "green" ],

}

export const docs = {
  name: 'Morio Healtchchecks Handler',
  description: `
This stream processing handler processes Morio healthchecks, which under the hood are generated by Elastic Heartbeat.

It will validate the healthcheck, and can produce a notification in case the healthcheck fails.
It can also check certificate expiry and cache the healthcheck results for dashboarding.

This handler can be further configured to control its behaviour.`,
  config: {
    cache: "Whether or not to cache healthcheck results.",
    certificate_notifications_days: 'Amount of days before ceritificate expiry a notification should be created',
    certificate_alarm_days: 'Amount of days before ceritificate expiry an alarm should be created',
    certificate_check: "Whether or not to verify the expiration date of TLS certificates (HTTP only)",
    enabled: "Set this to false to prevent this handler from being loaded by the Morio Tap service",
    modules: 'An optional list of Morio modules to use as filter for this handler',
    on_down: "What type of message to produce when a healthcheck fails. One of 'alarm', 'event', or 'notification'",
    topics: 'The Kafka topics to subscribe this event handler to',
    ttl: "The number of minutes for which to keep healthcheck data in the cache",
    up_values: "These are all the values that are considered a success for a healthcheck.",
  }
}

