# This holds the configuration wizard view settings for the Logstash specific config
# We call it connect but it's logstash under the hood
connect:
  about: Logstash about
  configId: logstash
  title: Connect
  type: info
  children:
    outputs:
      type: logstashOutputs
      label: Destinations
      about: |
        Add a destination for Morio to write data to.  
        Once configured, you can use the destination in your pipelines.
      blocks:
        elasticsearch:
          title: Elasticsearch
          about: Write data to Elasticsearch
          desc: fixme
        http:
          title: HTTP
          about: Write data over HTTP
          desc: fixme
        local_morio:
          title: Local Morio
          about: Write data to Morio
        remote_morio:
          title: Remote Morio
          about: Write data to a remote Morio deployment
          desc: Local morio adesc
    inputs:
      type: logstashInputs
      label: Sources
      about: |
        Add a source for Morio to read data from.  
        Once configured, you can use the source in your pipelines.
      blocks:
        aws_cloudwatch:
          title: AWS Cloudwatch
          about: Read data from Cloudwatch (Amazon Web Services)
          desc: Desc Generates random messages for test purposes
        azure_event_hubs:
          title: Azure Event Hubs
          about: Read data from Azure Event Hubs
          desc: Desc Generates random messages for test purposes
        generator:
          title: Generator
          about: Generates random messages for test purposes
          desc: Desc Generates random messages for test purposes
        http_poller:
          title: HTTP
          about: Read data over HTTP
          desc: |
            Allows you to poll an HTTP API for data. 

            Use this when you do not control the HTTP API and need Morio to poll it for you.
            If you do control the API, it's better to push data to Morio instead.
        morio:
          title: Morio
          about: Read streaming data from Morio
        morio_remote:
          title: Morio (remote)
          about: Read data from a remote Morio deployment
          desc: Use this to chain different Morio deployments together when you want this Morio instance to initiate the data transfer.

    pipelines:
      type: logstashPipelines
      label: Pipelines
      about: Pipelines about
