import { createHash } from 'crypto'
import fs from 'fs/promises'
import path from 'path'
import { glob } from 'glob'
import { config } from './config/tap.mjs'

/*
 * Add a banner to clarify where this code comes from
 */
const banner = `/*
 * This file is auto-generated by Morio.
 * Any manual changes will be lost.
 */`

// Whitespace to re-use
const nl = '\n'
const tab = '  '

/*
 * Helper function to glob a folder
 */
export async function globDir(folderPath, pattern = '*/index.mjs') {
  let list = []
  try {
    list = await glob(path.resolve(folderPath) + '/' + pattern)
  } catch (err) {
    if (err) console.log(err)
    return false
  }

  return list
}

export function hash(string) {
  // This is a non-security use of a hash, so md5 is fine
  return createHash('md5').update(string).digest('hex')
}

async function loadProcessorFiles(directory, pattern) {
  const folder = new URL(directory, import.meta.url)

  return await globDir(folder.pathname, pattern)
}

function asTopicList(input) {
  if (typeof input === 'string') return [input]
  if (Array.isArray(input)) return input
  if (typeof input === 'object') return Object.values(input)

  return []
}

function asModuleList(input) {
  if (input && typeof input === 'string' && input !== '*') return [input]
  if (Array.isArray(input)) return input
  if (typeof input === 'object') return Object.values(input)

  return '*'
}

async function ensureDynamicStreamProcessorCode() {
  const topics = new Set()
  const lut = {} // look-up table
  const imports = {}
  const processors = {}
  // The config.tap.imports key holds all the files we should import
  let i = 0
  for (const [id, proc] of Object.entries(config.tap?.imports || {})) {
    if (config.tap?.settings?.[id]?.enabled) {
      i++
      const importedAs = hash(proc.file)
      const subs = asTopicList(config.tap?.settings?.[id]?.topics || [])
      const mods = asModuleList(config.tap?.settings?.[id]?.modules || [])
      for (const topic of subs) {
        topics.add(topic)
        if (mods.length > 0) {
          if (typeof lut[topic] === 'undefined') lut[topic] = {}
          for (const mod of mods) {
            if (typeof lut[topic][mod] === 'undefined') lut[topic][mod] = {}
            if (config.tap.settings[id].datasets) {
              for (const dset of config.tap.settings[id].datasets) {
                if (typeof lut[topic][mod][dset] === 'undefined') lut[topic][mod][dset] = []
                lut[topic][mod][dset].push(id)
              }
            } else {
              if (typeof lut[topic][mod]['*'] === 'undefined') lut[topic][mod]['*'] = []
              lut[topic][mod]['*'].push(id)
            }
          }
        } else {
          if (typeof lut[topic] === 'undefined') lut[topic] = {}
          if (typeof lut[topic]['*'] === 'undefined') lut[topic]['*'] = {}
          if (typeof lut[topic]['*']['*'] === 'undefined') lut[topic]['*']['*'] = []
          lut[topic]['*']['*'].push(id)
        }
      }
      if (typeof imports[importedAs] === 'undefined') imports[importedAs] = { file: proc.file, processors: [] }
      imports[importedAs].processors.push(id)
      processors[id] = {
        importedAs,
        topics: subs,
        modules: mods,
        config: config.tap.settings[id],
        id,
        i,
        ...proc,
      }
      console.log(`Adding stream processor: ${id}`)
    }
    else console.log(`Skipping disabled stream processor: ${id}`)
  }

  /*
   * Holds import code
   */
  let imp = `${banner}${nl}
// We need a logger
import { log } from './src/tools.mjs'

// Stream processors`

  /*
   * Generate export code for all processors
   */
  let all = `${nl}${nl}/*${nl} * Simple object with all imports${nl} */${nl}export const code = {`
  for (const md5 of Object.keys(imports)) {
    imp += `${nl}import _${md5} from './processors/${imports[md5].file}'`
    for (const id of imports[md5].processors) {
      if (typeof processors[id].index === 'undefined') {
        // Export is an object describing the stream processor
        all += `${nl}  "${id}":  _${md5}, `
      } else {
        // Export is an array of objects describing stream processors
        all += `${nl}  "${id}":  _${md5}[${processors[id].index}], `
      }
    }
  }
  all += `${nl}}${nl}`

  /*
   * Generate export code from the lookup table
   */
  const lutData = {}
  for (const topic of Object.keys(lut)) {
    if (typeof lutData[topic] === 'undefined') lutData[topic] = {}
    for (const module of Object.keys(lut[topic])) {
      if (typeof lutData[topic][module] === 'undefined') lutData[topic][module] = {}
      for (const [dataset, d] of Object.entries(lut[topic][module])) {
        if (typeof lutData[topic][module][dataset] === 'undefined') lutData[topic][module][dataset] = []
        lutData[topic][module][dataset].push(typeof d.index === 'undefined'
          ? `${d.importedAs}`
          : `${d.importedAs}[${d.index}]`
        )
      }
    }
  }
  let lutCode = `${nl}${nl}/*${nl} * Object with all stream processors per topic/module/dataset${nl} */${nl}`
  lutCode += `export const lut = {${nl}`
  for (const topic of Object.keys(lut)) {
    lutCode += `  ${topic}: {${nl}`
    for (const module of Object.keys(lut[topic])) {
      lutCode += `    "${module}": {${nl}`
      for (const [dataset, d] of Object.entries(lut[topic][module])) {
        const h = d.map(handler => `code["${handler}"]`)
        lutCode += `      "${dataset}": [${nl}        ${h.join(",\n        ")}${nl}      ],${nl}`
      }
      lutCode += `    },${nl}`
    }
    lutCode += `  },${nl}`
  }
  lutCode += `}${nl}`

  /*
   * Now bring it all together and write to disk
   */
  const code = `${imp}${all}${lutCode}${nl}
export const topics = ${JSON.stringify([...topics])}
`
  await fs.writeFile('./loader.mjs', code)
}
/*
 * Get to work
 */
if (config.tap?.imports) ensureDynamicStreamProcessorCode()
else console.log(`No config with tap settings found on disk. Tap service cannot start.`)


