import fs from 'fs/promises'
import path from 'path'
import { glob } from 'glob'

/*
 * Add a banner to clarify where this code comes from
 */
const banner = `/*
 * This file is auto-generated by Morio core.
 * Any manual changes will be lost.
 */`

// Whitespace to re-use
const nl = "\n"
const tab = "  "

/*
 * Helper function to glob a folder
 */
export async function globDir(folderPath, pattern = '*/index.mjs') {
  let list = []
  try {
    list = await glob(path.resolve(folderPath) + '/' + pattern)
  } catch (err) {
    if (err) console.log(err)
    return false
  }

  return list
}

async function loadProcessorFiles(directory, pattern) {
  const folder = new URL(directory, import.meta.url)

  return await globDir(folder.pathname, pattern)
}

function asTopicList (input) {
  if (typeof input === 'string') return [input]
  if (Array.isArray(input)) return input
  if (typeof input === 'object') return Object.values(input)

  return []
}

async function ensureProcessorLoader() {
  const files = await loadProcessorFiles('./processors')
  const imports = {}
  const topics = new Set()
  for (const file of files) {
    const folder = path.basename(path.dirname(file))

    /*
     * Dynamically import the file. ESM is nice these days.
     */
    const module = await import(file)

    /*
     * Processors can be a single processors object, or an array of them
     */
    if (Array.isArray(module.default)) {
      for (const i in module.default) {
        const mod = module.default[i]
        if (mod.enabled){
          const subs = asTopicList(mod.topics)
          for (const topic of subs) topics.add(topic)
          if (typeof imports[folder] === 'undefined') imports[folder] = []
          imports[folder].push([`${folder}__${i}`, subs])
        }
      }
    }
    else if (module.default.enabled){
      const subs = asTopicList(module.default.topics)
      for (const topic of subs) topics.add(topic)
      imports[folder] = [ folder, subs ]
    }
  }

  /*
   * Holds import code
   */
  let imp = `${banner}${nl}${nl}// We need a logger${nl}import { log } from './src/tools.mjs'${nl}${nl}// Stream processors`

  /*
   * Holds allProcessors code
   */
  let ah = `${nl}${nl}/*${nl} * Simple object with all stream processors${nl} */${nl}export const allProcessors = {`

  const hpts = {}
  for (const folder in imports) {
    imp += `${nl}import ${folder} from './processors/${folder}/index.mjs'`
    if (typeof imports[folder][0] === 'string') {
      for (const topic of imports[folder][1]) {
        if (typeof hpts[topic] === 'undefined') hpts[topic] = new Set()
        hpts[topic].add(folder)
      }
      ah += `${nl}  ${folder}: ${folder}, `
    }
    else if (Array.isArray(imports[folder][0])) {
      let i = 0
      for (const entry of imports[folder]) {
        for (const topic of entry[1]) {
          if (typeof hpts[topic] === 'undefined') hpts[topic] = new Set()
          hpts[topic].add(entry[0])
        }
        ah += `${nl}  ${folder}__${i}: ${folder}[${i}], `
        i++
      }
    }
  }

  ah += `${nl}}${nl}`

  /*
   * Holds processorsPerTopic code
   */
  let hpt = `${nl}/*${nl} * Same stream processors but grouped by topic${nl} */${nl}export const processorsPerTopic = {`
  for (const [topic, processors] of Object.entries(hpts)) {
    hpt += `${nl}  ${topic}: [`
    for (const h of [...processors]) {
      if (Array.isArray(h)) {
        for (const hh of h) hpt += `${nl}    allProcessors.${hh},`
      }
      else hpt += `${nl}    allProcessors.${h},`
    }
    hpt += `${nl}  ],`
  }
  hpt += `${nl}}`

  /*
   * Now bring it all together and write to disk
   */
  const code = `${imp}${ah}${hpt}${nl}
export const topics = ${JSON.stringify([...topics])}
export const processorList = Object.keys(allProcessors)
`
  await fs.writeFile('./loader.mjs', code)
}

async function ensureModuleLoaders() {
  const files = await loadProcessorFiles('./processors', '*/modules/*.mjs')
  const imports = {}
  for (const file of files) {
    /*
     * We glob all files in one pass,
     * but we need to manage them per processor
     */
    const processor = path.basename(path.dirname(path.dirname(file)))
    if (typeof imports[processor] === 'undefined') imports[processor] = {}
    const filename = path.basename(file)
    if (filename.slice(-4) === '.mjs') {
      const module = filename.slice(0,-4)
      if (module !== 'index') {
        const importName = module.replaceAll('-', '_')
        imports[processor][module] = {
          imp: `import ${importName} from './${filename}'`,
          exp: `  "${module}": ${importName}`
        }
      }
    }
  }

  /*
   * Now write out the index.mjs loader files
   */
  for (const processor in imports) {
    const code = `${banner}
${Object.values(imports[processor]).map(h => h.imp).join(nl)}${nl}
export default {${nl}${Object.values(imports[processor]).map(h => h.exp).join(nl)}${nl}}${nl}`
    await fs.writeFile(`./processors/${processor}/modules/index.mjs`, code)
  }
}

ensureProcessorLoader()
ensureModuleLoaders()

