/*
 * This file is auto-generated by Morio.
 * Any manual changes will be lost.
 */

// We need a logger
import { log } from './src/tools.mjs'

// Stream processors
import audit from './processors/audit/index.mjs'
import checks from './processors/checks/index.mjs'
import events from './processors/events/index.mjs'
import logs from './processors/logs/index.mjs'
import metrics from './processors/metrics/index.mjs'

/*
 * Simple object with all stream processors
 */
export const allProcessors = {
  audit, 
  checks, 
  events, 
  logs, 
  metrics, 
}

/*
 * Same stream processors but grouped by topic
 */
export const processorsPerTopic = {
  audit: [
    allProcessors.audit,
  ],
  checks: [
    allProcessors.checks,
  ],
  events: [
    allProcessors.events,
  ],
  logs: [
    allProcessors.logs,
  ],
  metrics: [
    allProcessors.metrics,
  ],
}

export const topics = ["metrics","logs","events","checks","audit"]
export const processorList = []
for (const topic in processorsPerTopic) {
  for (const proc of processorsPerTopic[topic])
  processorList.push(proc.name)
}
