import { config } from "./config.mjs"
import modules from "./modules/index.mjs"

/*
 * This is a Morio Stream Processor, also known as a Tap Handler.
 *
 * It is designed to handle data in the 'audit' topic, which
 * typically holds data generated by Auditbeat agents,
 * although it can also process other data if it's well-formatted.
 *
 * ## Data Requirements
 *
 * This handler expects:
 *
 * - data.host.id to be set (will log a note if not)
 * - data.morio.module to be set (will log a note if note)
 *
 * It will hand of the data to a module-specific handler.
 * If that handler returns any data, it will cache data as audit data.
 */
const handler = config.enabled ? {
  ...config,
  /**
   * This method will be called for ever incoming message on the audit topic
   *
   * @param {object} data - The data from RedPanda
   * @param {obectt} tools - The tools object
   */
  method: (data, tools, topic) => {
    /*
     * Create note when host ID is missing
     */
    if (!data.host.id) tools.note(`[audit] Host lacks ID: : ${JSON.stringify(data)}`)

    /*
     * Hand over to module-specific logic
     */
    if (data?.morio?.module && typeof modules[data.morio.module] === 'function') {
      /*
       * Hand of to module-specific code to determine what to do
       */
      const result = modules[data.morio.module](data, tools)

      /*
       * Only update if we get data back from the module code
       */
      if (result) tools.cache.audit(result)
    }
    else if (config.log_unhandled) {
      tools.note(`[metrics] Cannot handle message`, data)
    }

  }
} : false

export default handler

export const info = {
  title: 'Audit data stream processor',
  about: `This stream processor will process audit data flowing through your Morio collection.

It can cache recent audit events, as well as enventify them for event-driven automation.
It also supports dynamic loading of module-specific logic.`,
  settings: {
    enabled: {
      title: 'Enable audit stream processor',
      dflt: true,
      type: 'list',
      list: [
        {
          val: false,
          label: 'Disabled'
        },
        {
          val: true,
          label: 'Enabled'
        },
      ]
    },
    topics: {
      dflt: ['audit'],
      title: 'List of topics to subscribe to',
      about: 'FIXME - description goes here',
      type: 'labels',
    },
    cache: {
      dflt: true,
      title: 'Cache audit data',
      type: 'list',
      list: [
        {
          val: false,
          label: 'Do not cache audit data (disable)',
        },
        {
          val: true,
          label: 'Cache recent audit data',
          about: 'Caching audit data allows consulting it through the dashboards provided by Morio&apos;s UI service'
        },
      ],
    },
    eventify: {
      dflt: true,
      title: 'Eventify audit data',
      type: 'list',
      list: [
        {
          val: false,
          label: 'Do not eventify audit data (disable)',
        },
        {
          val: true,
          label: 'Auto-create events based on audit data',
          about: 'Eventifyingaudit data allows for event-driven automation and monitoring based on audit information',
        },
      ],
    },
    ttl: {
      dflt: 2,
      title: 'fixme',
      type: 'number'
    },
  }
}
