## Run in NodeJS v20
FROM node:20-slim

# Make this folder our working directory
WORKDIR /morio/ui

## Map the charts folder to a shared location with core
RUN pwd && mkdir -p /etc/morio/shared/charts && mkdir ./public && cd /morio/ui/public && ln -s /etc/morio/shared/charts . && cd -

## Drop privleges and run NodeJS code via pm2
USER node
CMD ["npm", "run", "dev"]
