/*
 * This file is auto-generated by Morio Core
 * Any manual changes will be overwritten
 */

// Tap config for builting handler metrics
export const config = {
  "enabled": true,
  "topics": {
    "metrics": "metrics"
  },
  "modules": {},
  "cache": true,
  "ttl": 1,
  "cap": 300
}
