import { config } from "./config.mjs"

/*
 * This is a Morio handler to handle the metrics generated by
 * the morio-tap client module
 */
const handler = config.enabled ? {
  ...config.handler,
  method: (data, tools, topic) => {
    /*
     * Metricset: throughput
     */
    if (data.metricset?.name === 'throughput') tools.cache.metricset(data.morio.tap.throughput, data, config)
  }
} : null

export default handler

