# First thing to do is figure out how many nodes we should deploy
# init is a special key that serves as the entry point to the configuration wizard
init:
  # Typically the key is used as configKey, but in this case, it's specified explicitly
  # because the 'init' key has a special purpose.
  # This configKey value (or the key for other blocks) determines where the data will be
  # stored in the configuration (in this case under morio.node_count)
  configKey: morio.node_count
  next: morio.nodes
  type: list
  title: Node vs Cluster
  input:
    - val: 1
      label: Morio Node
      about: |
        - Setup a standalone Morio node
        - Recommended for small deployments
        - Provides a simpler setup with less moving parts
    - val: 3
      label: Morio Cluster
      about: |
        - Setup a 3-node Morio cluster
        - Recommended for larger deployments
        - Provides high availibility and horizontal scaling
    - label: Larger Morio cluster sizes
      about: |
        - Setup a larger Morio cluster
        - Recommended for increased throughput
        - Size matters, but bigger is not always better
      hide: Show larger Morio cluster sizes
      val:
        type: select
        values: [5, 7, 9, 11, 13, 15]
        labels:
          - 5 nodes
          - 7 nodes
          - 9 nodes
          - 11 nodes
          - 13 nodes
          - 15 nodes
        label: Cluster nodes
        about: Choose the amount of nodes in the Morio cluster

# Next thing we need is the names of the nodes
morio.nodes:
  type: strings
  count: '{{ CONFIG.morio.node_count }}'
  label: Nodes
  labels: 'Node {{ INDEX_PLUS_ONE }}'
  labelsTR: 'Enter the fully qualified domain name of node {{ INDEX_PLUS_ONE }}'
  about: Each Morio nodes needs a name that will resolve in DNS (an FQDN)
  placeholder: host.my.domain.com
  next: morio.display_name

# We also like a display name to refer to Morio as a whole
# Allowing for something more user-friendly, or differentating between different environments
morio.display_name:
  type: string
  label: Display Name
  about: A human-friendly name to refer to this Morio setup
  placeholder: Morio Production
  next:
    if:
      val: '{{ CONFIG.morio.node_count }}'
      as: number
    is: 1
    then: MORIO_VALIDATE_CONFIG
    else: morio.cluster_name

# For clusters, we also suggest/want/need a round-robin DNS address
morio.cluster_name:
  type: string
  label: Cluster Name
  about: |
    A round-robin DNS record for the entire Morio cluster. 
    This should resolve the the IP addresses of all cluster nodes.
  placeholder: cluster.my.domain.com
  next: MORIO_VALIDATE_CONFIG
