# First thing to do is figure out how many nodes we should deploy
# init is a special key that serves as the entry point to the configuration wizard
init:
  # Typically the key is used as configKey, but in this case, it's specified explicitly
  # because the 'init' key has a special purpose.
  # This configKey value (or the key for other blocks) determines where the data will be
  # stored in the configuration (in this case under morio.node_count)
  configKey: morio.node_count
  next: morio.nodes
  type: list
  title: Stand-Alone vs Clustered
  input:
    - val: 1
      label: Morio stand-alone
      about: Choose this to deploy a single Morio instance. Suitable for smnall to medium sized deployments, and a good choice to start with. You can always grow your setup later.
    - val: 3
      label: Morio cluster
      about: Choose this to deploy a Morio cluster with 3 nodes. Suitable when high availibility is required, or the amount of data to process is too great for a single node.
    - val: 
        hide: Need a larger setup?
        type: select
        values: [5,7,9,11,13,15]
        labels: 
          - 5 nodes
          - 7 nodes
          - 9 nodes
          - 11 nodes
          - 13 nodes
          - 15 nodes
        label: Cluster nodes
        about: Choose the amount of nodes in the Morio cluster
      label: Larger Morio cluster sizes
      about: Choose this to deploy a Morio cluster with higher number of nodes. Suitable when scaling horizontally is required to increase capacity.

# Next thing we need is the names of the nodes
morio.nodes:
  type: strings
  count: '{{ CONFIG.morio.node_count }}'
  label: Morio node names
  labels: "Node {{ INDEX_PLUS_ONE }}"
  labelsTR: "Enter the fully qualified domain name of node {{ INDEX_PLUS_ONE }}"
  about: Each Morio nodes needs a name that will resolve in DNS (an FQDN)
  placeholder: host.my.domain.com
  next: morio.name

# We also like a display name to refer to Morio as a whole
# Allowing for something more user-friendly, or differentating between different environments
morio.name:
  type: string
  label: Morio display name
  about: A human-friendly name to refer to this Morio setup
  placeholder: Morio Production
  next: 
    if: 
      val: '{{ CONFIG.morio.node_count }}'
      as: number
    is: 1
    then: MORIO_VALIDATE_CONFIG
    else: morio.rrdns

# For clusters, we also suggest/want/need a round-robin DNS address 
morio.rrdns:
  type: string
  label: Morio Cluster DNS name
  about: |
    A round-robin DNS record for the entire Morio cluster. 
    This should resolve the the IP addresses of all cluster nodes.
  placeholder: cluster.my.domain.com
  next: MORIO_VALIDATE_CONFIG


