## Stage 1: Build in NodeJS v20
FROM node:20-slim

## Make this folder our working directory
WORKDIR /morio/api

## Set environment variable to indicate this is production code
ENV NODE_ENV production

## Copy in source and config
COPY . .

## Install all the latest updates
## We need to bust the cache for this, or we'll get stale images
ARG CACHEBUST=1
RUN apt-get update && apt-get upgrade -y && apt-get install -y git vim

## Install dependencies
RUN npm i

## Install the pm2 process manager for NodeJS
RUN npm install pm2 -g

## Add a morio user to run the NodeJS code
RUN addgroup --system --gid ${GID:-2112} ${USER:-morio} \
  && adduser --system --uid ${UID:-2112} --gid ${GIS:-2112} --gecos "Morio User" --home=/home/morio ${USER:-morio} \
  && chown -R morio:morio /morio/api

## Copy the various PM2 scripts into the PATH
COPY ./bin/* /usr/local/bin/

## Drop privleges and run NodeJS code via pm2
USER ${USER:-morio}
CMD [ "pm2-runtime", "start", "/etc/morio/api/pm2.config.js" ]
