name: Publish moriod .deb package

on:
  # This should not run on every PR, but it's here for testing this workflow
  pull_request:
  #release:
  #  types: [published]

jobs:
  build_and_push_to_packagecloud:
    name: Build & Publish .deb Package
    runs-on: ubuntu-latest
    #
    # we build this on Debian 12, but it _should_ work for any .deb based distru
    #
    container: debian:bookworm
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build & Publish the .deb package
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: 'npm run ci:build:moriod:deb publish'

