name: Publish itsmorio/core OCI image

on:
  # This should not run on every PR, but it's here for testing this workflow
  pull_request:
  #release:
  #  types: [published]

jobs:
  build_and_push_to_registry:
    name: Build OCI Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build the OCI image
        run: 'npm run ci:build:core'

          #- name: Log in to Docker Hub
          #  uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          #  with:
          #    username: ${{ vars.DOCKER_USERNAME }}
          #    password: ${{ secrets.DOCKER_PAT }}

