#
# This action runs aspell on the markdown files for documentation
# To run this locallly, run this in the repository root:
#   - npm run spellcheck
#
name: Spellcheck Documentation

on:
  # We use branch protection, so run this on pull requests only
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Morio uses NodeJS 20 lts/iron
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache_node_modules
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install Aspell
        run: apt install -y aspell

      - name: Run aspell
        run: npm run ci:spellcheck
