name: Prettier (all files)

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --ignore-unknown --write ./core ./ui ./api ./shared ./schema ./scripts ./config
          commit_message: "[bot] Making the code prettier"
          commit_description: "This commit applies auto-formatting to the code. It was added in a pipeline by a bot."
