name: Publish moriod .rpm package

on:
  # This should not run on every PR, but it's here for testing this workflow
  pull_request:
  #release:
  #  types: [published]

jobs:
  build_and_push_to_packagecloud:
    name: Build & Publish .rpm Package
    runs-on: ubuntu-latest
    #
    # we build this on Debian 12, but it _should_ work for any .deb based distru
    #
    container: redhat/ubi
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Update dependencies
        run: 'yum update -y'

      - name: Install curl
        run: 'yum install -y curl'

      - name: Install nvm
        run: 'touch ~/.bash_profile && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash'

      - name: Install node
        run: 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && nvm install lts/iron'

      - name: Build & Publish the .deb package
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && nvm use lts/iron && npm run ci:build:moriod:rpm'

