#
# This runs unit tests for the core and api in CI
# To run these tests locally, you can run the following:
#
# - npm run test:core
# - npm run tsest:api
#
# Make sure to do so in the repository root
#
name: Run unit tests
on:
  pull_request:

jobs:
  test:
    # This needs to run on a self-hosted runner
    # we need a change
    runs-on: self-hosted
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}


      - name: Run unit tests
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ github.token }}
        shell: bash -l {0}  # Use login shell for nvm to work
        run: |
          export NVM_DIR="$HOME/.nvm"
          $NVM_DIR/nvm.sh
          nvm use lts/iron
          ./.github/workflows/unit-tests.sh
