function loadSettings () {
  /*
   * The settings are auto-generated by core and saved to disk, so let's load them
   */
  const file = process.env['MORIO_EDA_PLUGIN_SETTINGS'] || `/etc/morio/eda/morio-settings.js`
  const settings = require(file)

  return settings
}

/*
 * This parses an incoming message into structured data
 *
 * @param {object} message - The message as received from Kafka/RedPanda
 * @return {object} data - The structured data
 */
function parseKafkaMessage(message) {
  const data = {}
  data.timestamp = message.timestamp ? Number(message.timestamp) : null
  data.offset = message.offset ? Number(message.offset) : null
  try {
    data.data = JSON.parse(message.value)
  } catch (err) {
    data.data = message?.value ? message.value : null
  }

  return data
}

/*
 * This prepares data to be send to Kafka by parsing it into a JSON string
 *
 * @param {object|string|number} data - The data to be sent to Kafka/RedPanda
 * @return {string} data - The parsed data as a string
 */
function prepareKafkaData(data) {

  if (typeof data === 'string') return data
  if (typeof data === 'number') return `${data}`
  let str = ''
  try {
    str = JSON.stringify(data)
  } catch (err) {
    str = `Failed to parse message data as JSON inside prepareKafkaData`
  }

  return str
}

module.exports = {
  loadSettings,
  parseKafkaMessage,
  prepareKafkaData,
}
